---
author: Jed Roundy
format: pdf

---
# Install Packages and General Setup
```{r include = FALSE}
library(here)
library(tidyverse)
library(openai)
library(readxl)
library(R.utils)


source('../api_key.R')

Sys.setenv(
    OPENAI_API_KEY = api_key 
) 
```


# Read in Data
```{r include = FALSE}
filepath <-  here('Yogurt_Conjoint', 'Yogurt Design Grid.xlsx')

d <- read_excel(filepath, sheet = 2)

d <- rename(d, c(brand_num = brand...5, type_num = type...6, fat_num = fat...7, package_num = package...8, price_num = price...9, brand_name = brand...10, type_name = type...11, fat_name = fat...12, package_name = package...13, price_name = price...14))

d <- d |> select(-...1)
```

# Get Responses
```{r include=FALSE}
get_response <- function(n = 5, chat = FALSE, prompt, role, keywords, temp){

  #Change formatting and model based on chat TRUE/FALSE
  if(chat == TRUE){
    model <- 'gpt-3.5-turbo'
    prompt <- list(list('role' = 'system', 'content' = role), list('role' = 'user', 'content' = prompt))
  }
  
  if(chat == FALSE){
    model <- 'text-davinci-003'
  }

  
  #identify model and temperature wanted
  temp <- temp
  tokens <- 100
  

  #Use function based on chat argument
  if(chat == TRUE){
    response <- create_chat_completion(model = model, n = n, messages = prompt, temperature = temp, max_tokens = tokens)
  }
  
  if(chat == FALSE){
  response <- create_completion(model = model, n = n, prompt = prompt, temperature = temp, max_tokens = tokens, best_of = n )
  }
  
  #Create choices object  to access the choices directly
  choices <- response$choices
  
  #Create a text vector to store the text in
  text_v <- c()
  
  #Loop through each choice with appropriate access path
  for (i in 1:n){
    
    if(chat == TRUE){
      text_v <- c(text_v, choices[[4]][[i]])
    }
    
    if(chat == FALSE){
      text_v <- c(text_v, choices[[1]][[i]])
    }
  }
  
  #Create vector to store true/false string comparisons
  answer <- c()
  
  
  #Loop through individual responses
  for (string in text_v){
    
    is_true <- c()
    
    #Loop through the keywords
    for(keyword in keywords){
      
      #Append the is_true vector with the result of keyword search
      is_true <- c(is_true, grepl(keyword, string, ignore.case = TRUE))
    }
  
    #If there is more than 1 keyword found, then return inconclusive. Else, return the keyword that is found. 
    answer <- c(answer, ifelse(sum(is_true) > 1, 'Inconclusive', keywords[is_true]))
  }
  #Makes sure all elements are in a single vector
  answer <- unlist(answer, FALSE)

return(list(answer = answer, text_v = text_v))
#return(answer)  
}
```

# Conjoint Prompt
```{r}

conjoint_prompt <- function(role_num, prompt_num, brand_1, type_1, fat_1, package_1, price_1, brand_2, type_2, fat_2, package_2, price_2){
  
  
  #Numbers
  if(role_num ==1){
  role <- 'Imagine you are taking a consumer survey on yogurt. You are presented with three choices. Two choices will be to purchase an item with given attributes, and a third option to not purchase anything. Respond with ONLY the option number, 1,2,3. Do NOT include other information.'
}
  
#1-2-3 (OPTION ORDER)
if(prompt_num == 11){
  prompt <- paste0('Option 1: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option 2: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n', 'Option 3: I would not purchase either of the products.')
}
  
#1-3-2
  if(prompt_num == 12){
  prompt <- paste0('Option 1: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option 2: I would not purchase either of the products.', '\n', 'Option 3: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#2-1-3
  if(prompt_num == 13){
  prompt <- paste0('Option 1: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 2: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option 3: I would not purchase either of the products.')
}

#2-3-1
  if(prompt_num == 14){
  prompt <- paste0('Option 1: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 2: I would not purchase either of the products.', '\n', 'Option 3: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }
  
#3-1-2
  if(prompt_num == 15){
  prompt <- paste0('Option 1: I would not purchase either of the products.', '\n','Option 2: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option 3: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#3-2-1
  if(prompt_num == 16){
  prompt <- paste0('Option 1: I would not purchase either of the products.', '\n','Option 2: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 3: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }

  

   
  #Numbers
  if(role_num ==2){
  role <- 'Imagine you are taking a consumer survey on yogurt. You are presented with three choices. Two choices will be to purchase an item with given attributes, and a third option to not purchase anything. Respond with ONLY the option letter, A,B,C. Do NOT include any other information.'
  
  prompt_num <- sample(21:26, 1)
  }
  
#1-2-3 (OPTION ORDER)
if(prompt_num == 21){
  prompt <- paste0('Option A: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option B: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n', 'Option C: I would not purchase either of the products.')
}
  
#1-3-2
  if(prompt_num == 22){
  prompt <- paste0('Option A: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option B: I would not purchase either of the products.', '\n', 'Option C: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#2-1-3
  if(prompt_num == 23){
  prompt <- paste0('Option A: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option B: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option C: I would not purchase either of the products.')
}

#2-3-1
  if(prompt_num == 24){
  prompt <- paste0('Option A: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option B: I would not purchase either of the products.', '\n', 'Option C: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }
  
#3-1-2
  if(prompt_num == 25){
  prompt <- paste0('Option A: I would not purchase either of the products.', '\n','Option B: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option C: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#3-2-1
  if(prompt_num == 26){
  prompt <- paste0('Option A: I would not purchase either of the products.', '\n','Option B: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option C: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }
  return(c(role, prompt, prompt_num))
  
  #Numbers
  if(role_num == 3){
  role <- 'Imagine you are an individual who is young, white, and liberal, taking a consumer survey on yogurt. You are presented with three choices. Two choices will be to purchase an item with given attributes, and a third option to not purchase anything. Respond with ONLY the option number, 1,2,3. Do NOT include other information.'
  
  prompt_num <- sample(31:36, 1)
  }
  
#1-2-3 (OPTION ORDER)
if(prompt_num == 31){
  prompt <- paste0('Option 1: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option 2: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n', 'Option 3: I would not purchase either of the products.')
}
  
#1-3-2
  if(prompt_num == 32){
  prompt <- paste0('Option 1: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option 2: I would not purchase either of the products.', '\n', 'Option 3: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#2-1-3
  if(prompt_num == 33){
  prompt <- paste0('Option 1: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 2: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option 3: I would not purchase either of the products.')
}

#2-3-1
  if(prompt_num == 34){
  prompt <- paste0('Option 1: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 2: I would not purchase either of the products.', '\n', 'Option 3: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }
  
#3-1-2
  if(prompt_num == 35){
  prompt <- paste0('Option 1: I would not purchase either of the products.', '\n','Option 2: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option 3: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#3-2-1
  if(prompt_num == 36){
  prompt <- paste0('Option 1: I would not purchase either of the products.', '\n','Option 2: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 3: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }    

  if(role_num == 4){
  role <- 'Imagine you are an individual who is old, black, and republican, taking a consumer survey on yogurt. You are presented with three choices. Two choices will be to purchase an item with given attributes, and a third option to not purchase anything. Respond with ONLY the option number, 1,2,3. Do NOT include other information.'
  
  prompt_num <- sample(41:46, 1)
  }
  
#1-2-3 (OPTION ORDER)
if(prompt_num == 41){
  prompt <- paste0('Option 1: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option 2: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n', 'Option 3: I would not purchase either of the products.')
}
  
#1-3-2
  if(prompt_num == 42){
  prompt <- paste0('Option 1: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n','Option 2: I would not purchase either of the products.', '\n', 'Option 3: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#2-1-3
  if(prompt_num == 43){
  prompt <- paste0('Option 1: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 2: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option 3: I would not purchase either of the products.')
}

#2-3-1
  if(prompt_num == 44){
  prompt <- paste0('Option 1: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 2: I would not purchase either of the products.', '\n', 'Option 3: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }
  
#3-1-2
  if(prompt_num == 45){
  prompt <- paste0('Option 1: I would not purchase either of the products.', '\n','Option 2: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1, '\n', 'Option 3: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2)
  }
  
#3-2-1
  if(prompt_num == 46){
  prompt <- paste0('Option 1: I would not purchase either of the products.', '\n','Option 2: Brand:', brand_2, ' Type:', type_2, ' Fat:', fat_2, ' Packaging:', package_2, ' Price:', price_2, '\n','Option 3: Brand:', brand_1, ' Type:', type_1, ' Fat:', fat_1, ' Packaging:', package_1, ' Price:', price_1)
  }    
  
  
}


```


# Get the responses

```{r}
choice_v <- c()
text_v <- c()
prompt_v <- c()
task_v <- c()
concept_v <- c()
version_v <- c()

#Role 1 - Numbers
#Role 2 - Letters
role_num <- 1
if(role_num %in% c(1,3,4)){keywords = c('1', '2', '3')}
if(role_num == 2){keywords = c('A', 'B', 'C')}



#temperature setting
temperature <- 1

#Number of distinct tests performed
k = 10


for (task in seq(1, k*2, by = 2)){
    #Print task num
    print(task)
    # For each round, only grab two rows of data at a time 
    task_data <- d[task:(task+1), ]

    for(i in seq(1, 6)){
        
        prompt_num <- as.integer(paste0(role_num, i))
            
        # Create list of args for the prompt
        args <- list(role_num,prompt_num, task_data[1,'brand_name'], task_data[1, 'type_name'], task_data[1, 'fat_name'], task_data[1, 'package_name'], task_data[1, 'price_name'], task_data[2,'brand_name'], task_data[2, 'type_name'], task_data[2, 'fat_name'], task_data[2, 'package_name'], task_data[2, 'price_name'])

        # Call the prompt with the list of args
        cp <- do.call(conjoint_prompt, args = args)
        # Separate the role from the prompt
        role <- cp[1]
        prompt <- cp[2]
        prompt_num <- cp[3]

        api_call_successful <- FALSE

        repeat {
            tryCatch({
                withTimeout({
                    # API call
                    response <- get_response(n = 1, chat = TRUE, prompt = prompt, role = role, keywords = keywords, temp = temperature)

                    # Apply the responses of the choice and text to appropriate vectors
                    choice_v <- c(choice_v, unlist(response[1]))
                    text_v <- c(text_v, unlist(response[2]))
                    prompt_v <- c(prompt_v, prompt_num)
                    version_v <- c(version_v, task_data[1, 1][[1]])
                    version_v <- c(version_v, task_data[2, 1][[1]])
                    task_v <- c(task_v, task_data[1, 2][[1]])
                    task_v <- c(task_v, task_data[2, 2][[1]])
                    concept_v <- c(concept_v, task_data[1,3][[1]])
                    concept_v <- c(concept_v, task_data[2,3][[1]])

                    api_call_successful <- TRUE
                }, timeout = 5)  # Set timeout to 5 seconds
            }, error = function(e) {
                # Handle both timeout and other errors
                # Optionally log the error or take other actions
                 print("API call failed or timed out, retrying...")
            })

            if(api_call_successful) {
                break
            }
        }
    }
}



choice_v <- rep(choice_v, each = 2)
text_v <- rep(text_v, each = 2)
prompt_v <- rep(prompt_v, each = 2)

assign(paste0('data_','r_', role_num), data.frame(choice = choice_v, text = text_v, prompt = prompt_v, task = task_v, concept = concept_v, version = version_v))

columns_to_int <- c("prompt", "task", "concept", 'version')
data_r_1[columns_to_int] <- lapply(data_r_1[columns_to_int], as.integer)

mean(data_r_1$prompt)


data_r_1$choice <- as.factor(data_r_1$choice)
```

